table material_costs

	column PurchaseID
		dataType: string
		sourceColumn: PurchaseID

	column WBS_ID
		dataType: string
		sourceColumn: WBS_ID

	column PurchaseDate
		dataType: dateTime
		formatString: "yyyy-MM-dd"
		sourceColumn: PurchaseDate

	column Description
		dataType: string
		sourceColumn: Description

	column Quantity
		dataType: int64
		sourceColumn: Quantity

	column UnitPrice
		dataType: double
		formatString: "$#,##0.00"
		sourceColumn: UnitPrice

	column TotalActualCost
		dataType: double
		formatString: "$#,##0.00"
		sourceColumn: TotalActualCost

	partition material_costs-Partition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/frank/Desktop/Project Mng/Data/CSV/material_costs.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"Quantity", Int64.Type}, {"UnitPrice", type number}, {"TotalActualCost", type number}}, "en-US")
				in
				    Typed
