table physical_progress

	column ProgressID
		dataType: string
		sourceColumn: ProgressID

	column WBS_ID
		dataType: string
		sourceColumn: WBS_ID

	column RecordDate
		dataType: dateTime
		formatString: "yyyy-MM-dd"
		sourceColumn: RecordDate

	column PercentComplete
		dataType: double
		formatString: "0.00%"
		sourceColumn: PercentComplete

	column ReportedBy
		dataType: string
		sourceColumn: ReportedBy

	partition physical_progress-Partition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("c:/Users/frank/Desktop/Project Mng/Data/CSV/physical_progress.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
                        Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true]),
                        Typed = Table.TransformColumnTypes(Headers, {{"ProgressID", type text}, {"WBS_ID", type text}, {"RecordDate", type datetime}, {"PercentComplete", type number}, {"ReportedBy", type text}}, "en-US")
				in
                        Typed
