table projects

	column ProjectID
		dataType: string
		sourceColumn: ProjectID

	column ProjectName
		dataType: string
		sourceColumn: ProjectName

	column ProjectManager
		dataType: string
		sourceColumn: ProjectManager

	column BudgetAtCompletion_BAC
		dataType: double
		formatString: "$#,##0.00"
		sourceColumn: BudgetAtCompletion_BAC

	column StartDate
		dataType: dateTime
		formatString: "yyyy-MM-dd"
		sourceColumn: StartDate

	column EndDate
		dataType: dateTime
		formatString: "yyyy-MM-dd"
		sourceColumn: EndDate

	column Status
		dataType: string
		sourceColumn: Status

	partition projects-Partition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("c:/Users/frank/Desktop/Project Mng/Data/CSV/projects.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"BudgetAtCompletion_BAC", type number}, {"StartDate", type datetime}, {"EndDate", type datetime}}, "en-US")
				in
				    Typed
