table resource_assignments
	lineageTag: 7425fdfe-c724-4c13-a044-dcb8d22175c8

	column AssignmentID
		dataType: string
		lineageTag: 02900175-877b-4426-9c8b-c536f7ec5925
		summarizeBy: none
		sourceColumn: AssignmentID

		annotation SummarizationSetBy = Automatic

	column WBS_ID
		dataType: string
		lineageTag: 98b27d27-8255-4184-902d-feb09f4251e6
		summarizeBy: none
		sourceColumn: WBS_ID

		annotation SummarizationSetBy = Automatic

	column ResourceID
		dataType: string
		lineageTag: 4f3473d3-c927-4280-87e1-9cf79befebfd
		summarizeBy: none
		sourceColumn: ResourceID

		annotation SummarizationSetBy = Automatic

	column AllocatedHours
		dataType: int64
		formatString: 0
		lineageTag: 1fcfe868-1229-4729-8ccf-0504c160baaf
		summarizeBy: sum
		sourceColumn: AllocatedHours

		annotation SummarizationSetBy = Automatic

	partition resource_assignments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\Project Mng\Data\CSV\resource_assignments.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"AssignmentID", type text}, {"WBS_ID", type text}, {"ResourceID", type text}, {"AllocatedHours", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

