table resources

	column ResourceID
		dataType: string
		sourceColumn: ResourceID

	column ResourceName
		dataType: string
		sourceColumn: ResourceName

	column Role
		dataType: string
		sourceColumn: Role

	column HourlyRate
		dataType: double
		formatString: "$#,##0.00"
		sourceColumn: HourlyRate

	partition resources-Partition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("c:/Users/frank/Desktop/Project Mng/Data/CSV/resources.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"HourlyRate", type number}}, "en-US")
				in
				    Typed
