table wbs_elements

	column WBS_ID
		dataType: string
		sourceColumn: WBS_ID

	column ProjectID
		dataType: string
		sourceColumn: ProjectID

	column WBS_Code
		dataType: string
		sourceColumn: WBS_Code

	column ElementName
		dataType: string
		sourceColumn: ElementName

	column PlannedCost
		dataType: double
		formatString: "$#,##0.00"
		sourceColumn: PlannedCost

	column PlannedHours
		dataType: double
		sourceColumn: PlannedHours

	partition wbs_elements-Partition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("c:/Users/frank/Desktop/Project Mng/Data/CSV/wbs_elements.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"PlannedCost", type number}, {"PlannedHours", type number}}, "en-US")
				in
				    Typed
