table EVMCurrent
	lineageTag: c1a2b3d4-e5f6-7890-abcd-ef1234567890

	measure 'Total BAC' = SUM(EVMCurrent[bac])
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567891

	measure 'Total AC' = SUM(EVMCurrent[ac])
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567892

	measure 'Total EV' = SUM(EVMCurrent[ev])
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567893

	measure 'Total PV' = SUM(EVMCurrent[pv])
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567894

	measure 'Portfolio CPI' = DIVIDE([Total EV], [Total AC])
		formatString: 0.00
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567895

	measure 'Portfolio SPI' = DIVIDE([Total EV], [Total PV])
		formatString: 0.00
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567896

	measure 'Portfolio CV' = [Total EV] - [Total AC]
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567897

	measure 'Portfolio SV' = [Total EV] - [Total PV]
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567898

	measure 'Total EAC' = SUM(EVMCurrent[eac])
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567899

	measure 'Portfolio VAC' = [Total BAC] - [Total EAC]
		formatString: #,0
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567900

	measure 'Portfolio RAG' = IF([Portfolio CPI] < 0.9 || [Portfolio SPI] < 0.9, "Red", IF([Portfolio CPI] < 1.0 || [Portfolio SPI] < 1.0, "Amber", "Green"))
		formatString: General
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567901

	column project_id
		dataType: string
		isNullable: false
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567902
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column project_name
		dataType: string
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567903
		summarizeBy: none
		sourceColumn: project_name

		annotation SummarizationSetBy = Automatic

	column manager
		dataType: string
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567904
		summarizeBy: none
		sourceColumn: manager

		annotation SummarizationSetBy = Automatic

	column as_of_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567905
		summarizeBy: none
		sourceColumn: as_of_date

		variation Variation
			isDefault
			relationship: 775e52fd-7dec-4130-ab86-5eec335d675e
			defaultHierarchy: LocalDateTable_f8662c6c-eb24-40fd-86e2-8731435ddb98.Datohierarki

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567906
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567907
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567908
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567909
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column cpi
		dataType: double
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567910
		summarizeBy: sum
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column spi
		dataType: double
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567911
		summarizeBy: sum
		sourceColumn: spi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cv
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567912
		summarizeBy: sum
		sourceColumn: cv

		annotation SummarizationSetBy = Automatic

	column sv
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567913
		summarizeBy: sum
		sourceColumn: sv

		annotation SummarizationSetBy = Automatic

	column eac
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567914
		summarizeBy: sum
		sourceColumn: eac

		annotation SummarizationSetBy = Automatic

	column vac
		dataType: decimal
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567915
		summarizeBy: sum
		sourceColumn: vac

		annotation SummarizationSetBy = Automatic

	column cost_status
		dataType: string
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567916
		summarizeBy: none
		sourceColumn: cost_status

		annotation SummarizationSetBy = Automatic

	column schedule_status
		dataType: string
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567917
		summarizeBy: none
		sourceColumn: schedule_status

		annotation SummarizationSetBy = Automatic

	partition EVMCurrent = m
		mode: import
		source = let Source = Csv.Document(File.Contents("C:\\Users\\frank\\Desktop\\AI learn\\project controller\\data\\powerbi\\evm_current.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Types = Table.TransformColumnTypes(Headers, {{"project_id", type text}, {"project_name", type text}, {"manager", type text}, {"as_of_date", type date}, {"bac", Currency.Type}, {"ac", Currency.Type}, {"ev", Currency.Type}, {"pv", Currency.Type}, {"cpi", type number}, {"spi", type number}, {"cv", Currency.Type}, {"sv", Currency.Type}, {"eac", Currency.Type}, {"vac", Currency.Type}, {"cost_status", type text}, {"schedule_status", type text}}) in Types

