table EVMMonthly
	lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789012

	measure 'Monthly PV' = SUM(EVMMonthly[pv])
		formatString: #,0
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789013

	measure 'Monthly EV' = SUM(EVMMonthly[ev])
		formatString: #,0
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789014

	measure 'Monthly AC' = SUM(EVMMonthly[ac])
		formatString: #,0
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789015

	measure 'Monthly CPI' = DIVIDE([Monthly EV], [Monthly AC])
		formatString: 0.00
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789016

	measure 'Monthly SPI' = DIVIDE([Monthly EV], [Monthly PV])
		formatString: 0.00
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789017

	column project_id
		dataType: string
		isNullable: false
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789018
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column project_name
		dataType: string
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789019
		summarizeBy: none
		sourceColumn: project_name

		annotation SummarizationSetBy = Automatic

	column period_end
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789020
		summarizeBy: none
		sourceColumn: period_end

		variation Variation
			isDefault
			relationship: 8e0681d9-47ed-45de-88ad-6ba1062c3279
			defaultHierarchy: LocalDateTable_7524506b-f489-43cb-8442-a4657016fc60.Datohierarki

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789021
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789022
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789023
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789024
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column cpi
		dataType: double
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789025
		summarizeBy: sum
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column spi
		dataType: double
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789026
		summarizeBy: sum
		sourceColumn: spi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cv
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789027
		summarizeBy: sum
		sourceColumn: cv

		annotation SummarizationSetBy = Automatic

	column sv
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789028
		summarizeBy: sum
		sourceColumn: sv

		annotation SummarizationSetBy = Automatic

	column eac
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789029
		summarizeBy: sum
		sourceColumn: eac

		annotation SummarizationSetBy = Automatic

	column vac
		dataType: decimal
		lineageTag: 2b3c4d5e-6f78-9012-abcd-ef3456789030
		summarizeBy: sum
		sourceColumn: vac

		annotation SummarizationSetBy = Automatic

	partition EVMMonthly = m
		mode: import
		source = let Source = Csv.Document(File.Contents("C:\\Users\\frank\\Desktop\\AI learn\\project controller\\data\\powerbi\\evm_monthly.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Types = Table.TransformColumnTypes(Headers, {{"project_id", type text}, {"project_name", type text}, {"period_end", type date}, {"bac", Currency.Type}, {"pv", Currency.Type}, {"ev", Currency.Type}, {"ac", Currency.Type}, {"cpi", type number}, {"spi", type number}, {"cv", Currency.Type}, {"sv", Currency.Type}, {"eac", Currency.Type}, {"vac", Currency.Type}}) in Types

