table RiskSignals
	lineageTag: a7452973-8e14-4313-b3f7-240faa8bc99d

	column risk_id
		dataType: string
		isKey
		isNullable: false
		lineageTag: 895433d4-45e5-4c44-ad06-059bf02a93ce
		sourceColumn: risk_id

	column project_id
		dataType: string
		lineageTag: fda7f3f9-3237-4318-bc44-769f246c9bd1
		sourceColumn: project_id

	column project_name
		dataType: string
		lineageTag: b29279b2-5ef8-4c50-b2f7-f9f49f7069f1
		sourceColumn: project_name

	column severity
		dataType: string
		lineageTag: 181b17ea-4130-4e6d-b56a-0a5619085659
		sourceColumn: severity

	column risk_type
		dataType: string
		lineageTag: 0f50a661-a4be-4963-92b0-1255f09c896a
		sourceColumn: risk_type

	column message
		dataType: string
		lineageTag: 3c8043e0-c2c8-4a0c-80da-9dd7a986fd1f
		sourceColumn: message

	partition RiskSignals = m
		mode: import
		source = let Source = Csv.Document(File.Contents("C:\\Users\\frank\\Desktop\\AI learn\\project controller\\data\\powerbi\\risk_signals.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]), Types = Table.TransformColumnTypes(Headers, {{"risk_id", type text}, {"project_id", type text}, {"project_name", type text}, {"severity", type text}, {"risk_type", type text}, {"message", type text}}) in Types

