{
  "name": "Project_Wessels",
  "compatibilityLevel": 1570,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "PowerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "_Measures",
        "columns": [
          {
            "name": "MeasurePlaceholder",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MeasurePlaceholder"
          }
        ],
        "partitions": [
          {
            "name": "MeasuresPartition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [MeasurePlaceholder = _t]),\n    Type = Table.TransformColumnTypes(Source,{{\"MeasurePlaceholder\", Int64.Type}})\nin\n    Type"
            }
          }
        ],
        "measures": [
          {
            "name": "BAC",
            "expression": "SUM('wbs_elements'[PlannedCost])",
            "formatString": "$#,##0.00"
          },
          {
            "name": "Actual Labor Cost",
            "expression": "SUM('timesheets'[LaborCost])",
            "formatString": "$#,##0.00"
          },
          {
            "name": "Actual Material Cost",
            "expression": "SUM('material_costs'[TotalActualCost])",
            "formatString": "$#,##0.00"
          },
          {
            "name": "AC",
            "expression": "[Actual Labor Cost] + [Actual Material Cost]",
            "formatString": "$#,##0.00"
          },
          {
            "name": "Latest Percent Complete",
            "expression": "VAR SelectedDate = MAX('physical_progress'[RecordDate])\nRETURN\nSUMX(\n    VALUES('wbs_elements'[WBS_ID]),\n    VAR LatestWBSProgressDate = CALCULATE(MAX('physical_progress'[RecordDate]), 'physical_progress'[RecordDate] <= SelectedDate)\n    RETURN CALCULATE(MAX('physical_progress'[PercentComplete]), 'physical_progress'[RecordDate] = LatestWBSProgressDate)\n)",
            "formatString": "0.00%"
          },
          {
            "name": "Planned % Complete",
            "expression": "VAR StartDate = MIN('projects'[StartDate])\nVAR EndDate = MAX('projects'[EndDate])\nVAR CurrentDate = MAX('physical_progress'[RecordDate])\nRETURN\nIF(\n    EndDate <= StartDate,\n    0,\n    DIVIDE(DATEDIFF(StartDate, CurrentDate, DAY), DATEDIFF(StartDate, EndDate, DAY), 0)\n)",
            "formatString": "0.00%"
          },
          {
            "name": "EV",
            "expression": "SUMX(VALUES('wbs_elements'[WBS_ID]), [BAC] * [Latest Percent Complete])",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PV",
            "expression": "[BAC] * [Planned % Complete]",
            "formatString": "$#,##0.00"
          },
          {
            "name": "SV",
            "expression": "[EV] - [PV]",
            "formatString": "$#,##0.00"
          },
          {
            "name": "CV",
            "expression": "[EV] - [AC]",
            "formatString": "$#,##0.00"
          },
          {
            "name": "Variance RAG",
            "expression": "VAR Scenario = \"Baseline\"\nVAR CostVariancePct = DIVIDE([CV], [BAC], 0)\nVAR ScheduleVariancePct = DIVIDE([SV], [BAC], 0)\nVAR CostAmberThreshold = SWITCH(Scenario, \"Conservative\", 0.08, \"Baseline\", 0.12, \"Aggressive\", 0.18, 0.12)\nVAR CostRedThreshold = SWITCH(Scenario, \"Conservative\", 0.15, \"Baseline\", 0.20, \"Aggressive\", 0.30, 0.20)\nVAR ScheduleAmberThreshold = SWITCH(Scenario, \"Conservative\", 0.05, \"Baseline\", 0.10, \"Aggressive\", 0.15, 0.10)\nVAR ScheduleRedThreshold = SWITCH(Scenario, \"Conservative\", 0.10, \"Baseline\", 0.15, \"Aggressive\", 0.25, 0.15)\nRETURN\nSWITCH(\n    TRUE(),\n    ABS(CostVariancePct) >= CostRedThreshold || ABS(ScheduleVariancePct) >= ScheduleRedThreshold, \"Red\",\n    ABS(CostVariancePct) >= CostAmberThreshold || ABS(ScheduleVariancePct) >= ScheduleAmberThreshold, \"Amber\",\n    \"Green\"\n)",
            "formatString": "@"
          },
          {
            "name": "CPI",
            "expression": "DIVIDE([EV], [AC], 1.0)",
            "formatString": "0.00"
          },
          {
            "name": "SPI",
            "expression": "DIVIDE([EV], [BAC], 1.0)",
            "formatString": "0.00"
          },
          {
            "name": "EAC (Typical)",
            "expression": "DIVIDE([BAC], [CPI], [BAC])",
            "formatString": "$#,##0.00"
          },
          {
            "name": "VAC",
            "expression": "[BAC] - [EAC (Typical)]",
            "formatString": "$#,##0.00"
          }
        ]
      },
      {
        "name": "ScenarioSelection",
        "columns": [
          {
            "name": "Scenario",
            "dataType": "string",
            "sourceColumn": "Scenario"
          }
        ],
        "partitions": [
          {
            "name": "ScenarioSelection-Partition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = #table({\"Scenario\"}, {{\"Conservative\"}, {\"Baseline\"}, {\"Aggressive\"}})\nin\n    Source"
            }
          }
        ]
      },
      {
        "name": "projects",
        "columns": [
          {
            "name": "ProjectID",
            "dataType": "string",
            "sourceColumn": "ProjectID"
          },
          {
            "name": "ProjectName",
            "dataType": "string",
            "sourceColumn": "ProjectName"
          },
          {
            "name": "ProjectManager",
            "dataType": "string",
            "sourceColumn": "ProjectManager"
          },
          {
            "name": "BudgetAtCompletion_BAC",
            "dataType": "double",
            "sourceColumn": "BudgetAtCompletion_BAC",
            "formatString": "$#,##0.00"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "projects-Partition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\Users\\frank\\Desktop\\Project Mng\\Data\\CSV\\projects.csv\"),[Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true])\nin\n    Headers"
            }
          }
        ]
      },
      {
        "name": "wbs_elements",
        "columns": [
          {
            "name": "WBS_ID",
            "dataType": "string",
            "sourceColumn": "WBS_ID"
          },
          {
            "name": "ProjectID",
            "dataType": "string",
            "sourceColumn": "ProjectID"
          },
          {
            "name": "WBS_Code",
            "dataType": "string",
            "sourceColumn": "WBS_Code"
          },
          {
            "name": "ElementName",
            "dataType": "string",
            "sourceColumn": "ElementName"
          },
          {
            "name": "PlannedCost",
            "dataType": "double",
            "sourceColumn": "PlannedCost",
            "formatString": "$#,##0.00"
          },
          {
            "name": "PlannedHours",
            "dataType": "double",
            "sourceColumn": "PlannedHours"
          }
        ],
        "partitions": [
          {
            "name": "wbs_elements-Partition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\Users\\frank\\Desktop\\Project Mng\\Data\\CSV\\wbs_elements.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true])\nin\n    Headers"
            }
          }
        ]
      },
      {
        "name": "resources",
        "columns": [
          {
            "name": "ResourceID",
            "dataType": "string",
            "sourceColumn": "ResourceID"
          },
          {
            "name": "ResourceName",
            "dataType": "string",
            "sourceColumn": "ResourceName"
          },
          {
            "name": "Role",
            "dataType": "string",
            "sourceColumn": "Role"
          },
          {
            "name": "HourlyRate",
            "dataType": "double",
            "sourceColumn": "HourlyRate",
            "formatString": "$#,##0.00"
          }
        ],
        "partitions": [
          {
            "name": "resources-Partition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\Users\\frank\\Desktop\\Project Mng\\Data\\CSV\\resources.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true])\nin\n    Headers"
            }
          }
        ]
      },
      {
        "name": "timesheets",
        "columns": [
          {
            "name": "TimesheetID",
            "dataType": "string",
            "sourceColumn": "TimesheetID"
          },
          {
            "name": "ResourceID",
            "dataType": "string",
            "sourceColumn": "ResourceID"
          },
          {
            "name": "WBS_ID",
            "dataType": "string",
            "sourceColumn": "WBS_ID"
          },
          {
            "name": "WorkDate",
            "dataType": "dateTime",
            "sourceColumn": "WorkDate"
          },
          {
            "name": "HoursWorked",
            "dataType": "double",
            "sourceColumn": "HoursWorked"
          },
          {
            "name": "ApprovalStatus",
            "dataType": "string",
            "sourceColumn": "ApprovalStatus"
          },
          {
            "name": "LaborCost",
            "dataType": "double",
            "sourceColumn": "LaborCost",
            "formatString": "$#,##0.00"
          }
        ],
        "partitions": [
          {
            "name": "timesheets-Partition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\Users\\frank\\Desktop\\Project Mng\\Data\\CSV\\timesheets.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true]),\n    Types = Table.TransformColumnTypes(Headers, {\"HoursWorked\", type number}),\n    MergeRes = Table.NestedJoin(Types, {\"ResourceID\"}, resources, {\"ResourceID\"}, \"res\", JoinKind.LeftOuter),\n    ExpandRes = Table.ExpandTableColumn(MergeRes, \"res\", {\"HourlyRate\"}, {\"HourlyRate\"}),\n    TypeRate = Table.TransformColumnTypes(ExpandRes, {\"HourlyRate\", type number}),\n    AddLabor = Table.AddColumn(TypeRate, \"LaborCost\", each [HoursWorked] * [HourlyRate], type number)\nin\n    AddLabor"
            }
          }
        ]
      },
      {
        "name": "material_costs",
        "columns": [
          {
            "name": "PurchaseID",
            "dataType": "string",
            "sourceColumn": "PurchaseID"
          },
          {
            "name": "WBS_ID",
            "dataType": "string",
            "sourceColumn": "WBS_ID"
          },
          {
            "name": "PurchaseDate",
            "dataType": "dateTime",
            "sourceColumn": "PurchaseDate"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice",
            "formatString": "$#,##0.00"
          },
          {
            "name": "TotalActualCost",
            "dataType": "double",
            "sourceColumn": "TotalActualCost",
            "formatString": "$#,##0.00"
          }
        ],
        "partitions": [
          {
            "name": "material_costs-Partition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\Users\\frank\\Desktop\\Project Mng\\Data\\CSV\\material_costs.csv\"),[Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true])\nin\n    Headers"
            }
          }
        ]
      },
      {
        "name": "physical_progress",
        "columns": [
          {
            "name": "ProgressID",
            "dataType": "string",
            "sourceColumn": "ProgressID"
          },
          {
            "name": "WBS_ID",
            "dataType": "string",
            "sourceColumn": "WBS_ID"
          },
          {
            "name": "RecordDate",
            "dataType": "dateTime",
            "sourceColumn": "RecordDate"
          },
          {
            "name": "PercentComplete",
            "dataType": "double",
            "sourceColumn": "PercentComplete"
          },
          {
            "name": "ReportedBy",
            "dataType": "string",
            "sourceColumn": "ReportedBy"
          }
        ],
        "partitions": [
          {
            "name": "physical_progress-Partition",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Csv.Document(File.Contents(\"C:\\Users\\frank\\Desktop\\Project Mng\\Data\\CSV\\physical_progress.csv\"),[Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true])\nin\n    Headers"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_project_wbs",
        "fromTable": "wbs_elements",
        "fromColumn": "ProjectID",
        "toTable": "projects",
        "toColumn": "ProjectID"
      },
      {
        "name": "rel_wbs_timesheets",
        "fromTable": "timesheets",
        "fromColumn": "WBS_ID",
        "toTable": "wbs_elements",
        "toColumn": "WBS_ID"
      },
      {
        "name": "rel_resources_timesheets",
        "fromTable": "timesheets",
        "fromColumn": "ResourceID",
        "toTable": "resources",
        "toColumn": "ResourceID"
      },
      {
        "name": "rel_wbs_material_costs",
        "fromTable": "material_costs",
        "fromColumn": "WBS_ID",
        "toTable": "wbs_elements",
        "toColumn": "WBS_ID"
      },
      {
        "name": "rel_wbs_physical_progress",
        "fromTable": "physical_progress",
        "fromColumn": "WBS_ID",
        "toTable": "wbs_elements",
        "toColumn": "WBS_ID"
      }
    ]
  }
}