table timesheets

	column TimesheetID
		dataType: string
		sourceColumn: TimesheetID

	column ResourceID
		dataType: string
		sourceColumn: ResourceID

	column WBS_ID
		dataType: string
		sourceColumn: WBS_ID

	column WorkDate
		dataType: dateTime
		formatString: "yyyy-MM-dd"
		sourceColumn: WorkDate

	column HoursWorked
		dataType: double
		sourceColumn: HoursWorked

	column ApprovalStatus
		dataType: string
		sourceColumn: ApprovalStatus

	column LaborCost
		dataType: double
		formatString: "$#,##0.00"
		sourceColumn: LaborCost

	partition timesheets-Partition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/frank/Desktop/Project Mng/Data/CSV/timesheets.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalarTypes=true]),
				    Types = Table.TransformColumnTypes(Headers, {"HoursWorked", type number}),
				    MergeRes = Table.NestedJoin(Types, {"ResourceID"}, resources, {"ResourceID"}, "res", JoinKind.LeftOuter),
				    ExpandRes = Table.ExpandTableColumn(MergeRes, "res", {"HourlyRate"}, {"HourlyRate"}),
				    TypeRate = Table.TransformColumnTypes(ExpandRes, {"HourlyRate", type number}),
				    AddLabor = Table.AddColumn(TypeRate, "LaborCost", each [HoursWorked] * [HourlyRate], type number)
				in
				    AddLabor
